data:
  path: 'E:/pythonWorkSpace/PyTorch/Datasets/celeba/images/*.jpg'
  celebA_center_crop: True
  fid_file: 'E:/pythonWorkSpace/PyTorch/Datasets/celeba/fid_files/celeba_64.npz'
model:
  bounding_box_generator_kwargs:
    scale_range_min: [0.21, 0.21, 0.21]
    scale_range_max: [0.21, 0.21, 0.21]
    trans_range_min: [0., 0., 0.]
    trans_range_max: [0., 0., 0.]
    rotation_range: [0.40278, 0.59722]
  generator_kwargs:
    range_v: [0.4167, 0.5]
    fov: 10
training:
  out_dir: GIRAFFE/out/celeba64
rendering:
  render_program: ['object_rotation', 'interpolate_app', 'interpolate_shape']