data:
  path: ../datasets/comprehensive_cars/images/*.jpg
  fid_file: ../datasets/comprehensive_cars/fid_files/comprehensiveCars_64.npz
  random_crop: True
model:
  bounding_box_generator_kwargs:
    scale_range_min: [0.2, 0.16, 0.16]
    scale_range_max: [0.25, 0.2, 0.2]
    translation_range_min: [-0.22, -0.12, 0.]
    translation_range_max: [0.22, 0.12, 0.]
  generator_kwargs:
    range_v: [0.41667, 0.5]
    fov: 10
training:
  out_dir:  out/cars64
rendering:
  render_program: ['object_translation_vertical', 'object_translation_horizontal', 'object_rotation', 'interpolate_app', 'interpolate_shape', 'interpolate_app_bg', 'render_add_cars']